- name: Create directory for certificates
  ansible.builtin.file:
    path: ../../certs
    state: directory

- name: Generate private key
  openssl_privatekey:
    path: ../../certs/iconserver.key
    size: 4096
    type: RSA
    mode: 0400
    owner: ec2-user #Change owner
    group: ec2-user #Change group

- name: Generate self-signed certificate
  openssl_certificate:
    path: ../../certs/iconserver.crt
    privatekey_path: ../../certs/iconserver.key
    provider: selfsigned
    mode: 0444
    owner: ec2-user #Change owner
    group: ec2-user #Change group
