- name: Create/Ensure directory exists
  file:
    path: /opt/iconserver
    state: directory
    mode: '0755' 

- name: Copy Docker Compose template file
  copy:
    src: ../../../templates/docker-compose.yml
    dest: /opt/iconserver/docker-compose.yml

- name: Create certificates directory
  file:
    path: /opt/iconserver/certs
    state: directory

- name: Copy certificate
  copy:
    src: /home/ec2-user/AssesmentRepo/certs/iconserver.crt #Absolute path
    dest: /opt/iconserver/certs/iconserver.crt

- name: Copy private key
  copy:
    src: /home/ec2-user/AssesmentRepo/certs/iconserver.key #Absolute path
    dest: /opt/iconserver/certs/iconserver.key

- name: Start Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/iconserver/
