- name: Install Docker for Debian OS
  apt:
    name: docker.io
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker for RedHat OS
  yum:
    name: docker
    state: present
  when: ansible_os_family == "RedHat"

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'
